name: Combined DSA Sync

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  sync_leetcode:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Sync LeetCode Submissions
        uses: joshcai/leetcode-sync@v1.7
        with:
          github-token: ${{ github.token }}
          leetcode-csrf-token: ${{ secrets.CSRFTOKEN }}
          leetcode-session: ${{ secrets.LEETCODE_SESSION }}
          destination-folder: solutions/leetcode
          verbose: true

  sync_gfg:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Sync GFG Submissions
        uses: gaurav-gfg/gfg-scraper@v1
        with:
          gfg-username: ${{ secrets.GFG_USERNAME }}
          gfg-password: ${{ secrets.GFG_PASSWORD }}
          destination-folder: solutions/gfg

  sync_codeforces:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Sync Codeforces Submissions
        uses: ankit-gupta-24/codeforces-sync@v1
        with:
          handle: ${{ secrets.CF_HANDLE }}
          session_id: ${{ secrets.CF_SESSION }}
          destination-folder: solutions/codeforces
